### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 94080) exited unexpectedly

### ISSUE THREAD

**Issue by jiandandan001** [qibao77/CFSNet#7]
Thank you for sharing the code.

I run the deblocking code and have the following problem. Could you know the reason? Thanks.

  File "G:\Anaconda\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "G:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "G:\Anaconda\lib\queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 53, in <module>
    for data in test_loader:
  File "G:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "G:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "G:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 931, in _get_data
    success, data = self._try_get_data()
  File "G:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 94080) exited unexpectedly

**Comment by jiandandan001** [comment]
I re-run this code successfully with the Linux system. However, i have another question.
For image deblocking, I use the official model provided by you. I found that the results at QF =10 are not very good, in terms of bot h subjective and objective qualities.  The results at QF = 20/30/40 are reasonable. 
Could you help me check the model, or could you share me the deblocked images of classic5 and LIVE1?  Thanks.

**Comment by YuLvS** [comment]
Hi! @jiandandan001,
We've checked again and are sure the shared model is fine, with which I've again successfully run the codes and got the same results with the ones proposed in the paper (29.36 dB at q=10). The dataset is available and can be found in [Google Cloud Disk](https://drive.google.com/drive/folders/1C0VjWZr2dVQsPyN9jXzGxR-Y0iR9oX0A).

**Comment by YuLvS** [comment]
Hi! @jiandandan001,
We've checked again and are sure the shared model is fine, with which I've again successfully run the codes on the shared dataset ([Google Cloud Disk](https://drive.google.com/drive/folders/1C0VjWZr2dVQsPyN9jXzGxR-Y0iR9oX0A)) and got the same results with the ones proposed in the paper (29.36 dB at q=10).

**Comment by jimyug** [comment]
Hi! @jiandandan001,
We've checked again and are sure the shared model is fine, with which I've again successfully run the codes on the shared dataset ([Google Cloud Disk](https://drive.google.com/drive/folders/1C0VjWZr2dVQsPyN9jXzGxR-Y0iR9oX0A)) and got the same results as the ones proposed in the paper (29.36 dB at q=10).
